frr version 8.1
frr defaults traditional
hostname strongswan-router
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65001
 neighbor 10.0.255.30 remote-as 65515
 neighbor 10.0.255.30 ebgp-multihop 255
 neighbor 10.0.255.30 update-source 192.168.254.4
 !
 address-family ipv4 unicast
  network 192.168.0.0/16
  neighbor 10.0.255.30 activate
 exit-address-family
!
line vty
!
