config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn %default
    ikelifetime=1440m
    keylife=60m
    rekeymargin=3m
    keyingtries=%forever
    keyexchange=ikev2
    authby=secret
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s

conn azure-s2s
    left=192.168.254.4
    leftid=<PIP_STRONGSWAN_ROUTER>
    leftsubnet=192.168.0.0/16
    right=4.223.57.251
    rightid=4.223.57.251
    rightsubnet=10.0.0.0/16
    ike=aes256-sha256-modp2048,aes256-sha1-modp1024!
    esp=aes256-sha256,aes256-sha1!
    auto=add
